language: node_js
node_js:
 - lts/*

install:
  - npm install

branches:
  only:
    - master

jobs:
  include:
    - stage: test
      if: type = pull_request
      script: npm run lint
    - stage: build
      if: type = pull_request
      script: npm run build
    - stage: deploy
      if: type = push
      script: npm run lint
      script: npm run build
